sudo: false
language: java
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential execstack
script:
  - ./build_kerberos_image.sh
services:
  - docker
after_success:
  - travis/publish.sh
